### PR TITLE
Fix LoadingIndicator not showing when Camera or other Modals are showing

### PR DESCRIPTION
**Pull request by kefahB**
Hi @NathanWalker 

This fix the Loader is showing behind the camera or the modal.

### CODE REVIEW

**Review by NathanWalker — APPROVED** [review]
Thank you!

**Comment by NathanWalker** [comment]
Published with 4.3.0

**Comment by kefahB** [comment]
I just found same thing on Android :/ getSupportFragment isn't part of `Application.android.foregroundActivity` we should reverse the condition, but I am about trying to make a loop throw class to find the `FragmentActivity`

**Comment by kefahB** [comment]
I mean [this line](https://github.com/nstudio/nativescript-plugins/blob/36cfe10969416b37cd1dcc79b11a38493c5b3740/packages/nativescript-loading-indicator/index.android.ts#L339)

**Pull request merged**
