### PR TITLE
Added Background Audio implementation to Exoplayer

### PR DESCRIPTION
**Pull request by alexgritton**
It looks like the implementation for the backgroundAudio flag was removed when migrating this to nativescript-plugins. I've added that back into this plugin.

### CODE REVIEW

**Comment by NathanWalker** [comment]
@alexgritton thanks for this! Possible to merge in latest master? It may help resolve the conflicted files and help keep the formatting changes down to help see the actual changeset in the PR 🤗

**Comment by NathanWalker** [comment]
Or if you could add `NathanWalker` as contributor to your fork I can also update pull in upstream master to update this PR.

**Comment by alexgritton** [comment]
@NathanWalker I'll be on vacation until January 5th and can resolve it then. Otherwise I've added you as a contributor to the fork.

**Comment by natebgurutech** [comment]
Thanks for working on this!  It's a feature I really need.  Any updates on when this can get merged in?

**Comment by alexgritton** [comment]
Sorry for the delay, I've resolved the conflicts.

**Comment by NathanWalker** [comment]
excellent thanks @alexgritton !

**Comment by NathanWalker** [comment]
published with 5.0.5 now.

**Pull request merged**
