### PR TITLE
[Exoplayer] Upgraded Gradle dependency from 2.11.1 to 2.17.1

### PR DESCRIPTION
**Pull request by alexander-mai**
* the applicaton build failed because the dependency `com.google.android.exoplayer:exoplayer:2.11.1` was not found
* upgraded outdated gradle dependency to 2.17.1
* added typings for exoplayer 2.17.1 created with dts-generator
* updated exoplayer android implementation

### CODE REVIEW

**Comment by NathanWalker** [comment]
awesome thank you!

**Comment by DiogoSilvaEBS** [comment]
Hi. Now the methods exposed by the library don't work in my project. Events are not emitted, properties do not work (autostart for example). It seems that the library is not interacting correctly with the exoplayer. Do you know anything about this?

**Comment by alexander-mai** [comment]
Have you tried the changed version @DiogoSilvaEBS? I currently released version 5.0.9 doesn't contain the changes.
I tried the demos for the exoplayer before commiting and all worked fine. Only the subtitles didn't work, but they also didn't before the change.
Which properties are not working?

**Comment by DiogoSilvaEBS** [comment]
> Have you tried the changed version @DiogoSilvaEBS? I currently released version 5.0.9 doesn't contain the changes. I tried the demos for the exoplayer before commiting and all worked fine. Only the subtitles didn't work, but they also didn't before the change. Which properties are not working?

Hi @alexander-mai. 
We are not using the 5.0.9 version that is on npm, we are using the version that contains your latest changes (including this merge). We are also not using the native exoplayer controls, we have our own UI that calls methods from this library, like play, pause, and so on. It seems that none of the events and functions are working.
We re-installed a version with your changes that are already in the master and we did a basic test with the autoplay property and the event (playbackReady) and neither works.

image
image
image

The video appears but is not autoplayed and the (playbackReady) event does not work as it does not call the test() function in the component.

Any ideas?

**Comment by aaniceto** [comment]
I have the same problem. Can’t play the video if calling the play method, which is needed if not using the native exoplayer UI.

**Comment by alexander-mai** [comment]
I'll take a look at the problem tomorrow.

**Comment by aaniceto** [comment]
Let me know if you need any input/test or demo code from me. Thanks

**Comment by alexander-mai** [comment]
I fixed the autoplay and play function problem in https://github.com/nstudio/nativescript-plugins/pull/92.

The problem with the events is not fixed. I'm not sure if is was working before. The EventEmitter called in the iOS and Android implementation was defined (common.ts, line 98), but never instanciated.
```TypeScript
public _emit: any;
```
Maybe we could use the Implementation of the original video-player plugin for event emitting.

**Comment by alexander-mai** [comment]
Have you tried my changes changes in PR https://github.com/nstudio/nativescript-plugins/pull/92 @DiogoSilvaEBS and @aaniceto?

**Comment by Tronix117** [comment]
Hello, it seems events are still not firing, but it was definitely working pre v6

**Pull request merged**
