### PR TITLE
Feat(carousel): added nativescript-carousel plugin 

### PR DESCRIPTION
**Pull request by grigala**
Todos:
- [ ] add demos 

/cc @NathanWalker, @bradmartin, @triniwiz ref: https://github.com/manijak/nativescript-carousel/pull/203#issuecomment-1025502707

### CODE REVIEW

**Comment by NathanWalker** [comment]
@grigala this is awesome great job 👏 and thank you. If only adding a demo is left we can probably go ahead to merge and release a version. Is this moving of https://github.com/grigala/nativescript-carousel to here? If so we can help bring the demo over from there.

**Comment by grigala** [comment]
Hi @NathanWalker, yes, only demos are missing, haven't had time to configure them. 

> Is this moving of https://github.com/grigala/nativescript-carousel to here? If so we can help bring the demo over from there.

That is my fork of https://github.com/manijak/nativescript-carousel, where I fixed the Gradle 7 compatibility issue. Tiny change, but this will cause a lot of problems when people start to migrate/target Android 12. So it would be great to have a somewhat working version out there. 

The project does have some demos included, and actually you have it forked as well https://github.com/NathanWalker/nativescript-carousel 😁

**Review by NathanWalker — APPROVED** [review]

**Comment by NathanWalker** [comment]
I'll plan on bumping major to 8.0 to make it clear.

**Comment by NathanWalker** [comment]
@grigala I noticed the original author merged some updates, so you know if he published them? If not we could go ahead and publish it under scope this week (may just try to reach out to them).

**Comment by grigala** [comment]
> @grigala I noticed the original author merged some updates, do you know if he published them? If not we could go ahead and publish it under scope this week (may just try to reach out to them).

No he didn't. 😔

**Pull request merged**
