### PR TITLE
[loading-indicator] Fix current activity

### PR DESCRIPTION
**Pull request by kefahB**
@NathanWalker,

Sorry I didn't know why this commit was discarded! maybe because my fork wasn't updated ?!

### CODE REVIEW

**Comment by NathanWalker** [comment]
That’s what this does: https://github.com/NativeScript/NativeScript/blob/2cb26c2231e8dfcce657b6f63359d24a8c7217ed/packages/core/utils/android/index.ts#L20

**Comment by kefahB** [comment]
Yes I know but strangely I tested the 4.3.1 and it doesn't work after a camera open or barcode sacn .. the condition should be reversed in order to work, if we put `Application.android.startActivity` first the loader is showing otherwise it doesn't :

```ts

export function getCurrentActivity() {
	if (!Application) {
		return null;
	}
	return Application.android.startActivity || Application.android.foregroundActivity;
}
```

**Comment by kefahB** [comment]
I use `@nstudio/nativescript-barcodescanner`, after the scan `Application.android.foregroundActivity`  return zixing activity and not the app activity, for that putting `startActivity`  in that case make it working .. I have done several test and it seams to work as expected

**Comment by kefahB** [comment]
we can add a little helper instead of writing the condition each time with the reversed condition or if you think that the reversed condition doesn't have a negative impact you can edit the `getCurrentActivity` at the `Core'

**Comment by NathanWalker** [comment]
That’s interesting - ok let’s do that 
; if able to just add internal utility here to switch order and we’ll post update to finalize that. We can consider a change later in core of order needs to ultimately switch there.

**Review by NathanWalker — APPROVED** [review]

**Comment by NathanWalker** [comment]
Published with 4.3.2 thanks again @kefahB

**Pull request merged**
